name: Terraform Deployment

on:
  push:
    branches:
      - dev  # Change to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
      STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
      CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
      STORAGE_BLOB_NAME: ${{ secrets.STORAGE_BLOB_NAME }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: latest  # Change to your desired Terraform version

    - name: Initialize Terraform
      working-directory: ./terraform
      run: terraform init

    - name: Terraform Plan
      id: tf-plan  
      working-directory: ./terraform
      run: terraform plan -out=tfplan.out

    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply -auto-approve tfplan.out

    - name: Clean up Terraform plan
      working-directory: ./terraform
      run: rm tfplan.out
