name: 'Terraform'


on:
  push:
    branches:
    - dev
    paths:
    - '.github/workflows/terraform.yml'  
    - 'terraform/*'
    - 'terraform/streamlit/*'

jobs:
  terraform:
    name: Deploy to azure
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
      TF_VAR_STORAGE_BLOB_NAME: ${{ secrets.STORAGE_BLOB_NAME }}
      TF_VAR_STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME}}
      CLIENT_ID_AD: ${{ secrets.CLIENT_ID_AD }}

      TF_VERSION: latest

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: $TF_VERSION
          
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
    # This is a snowflake secrets example
      - name: Generate secrets.toml file
        run: |
          echo "[connections.snowpark]                               
          account = $(echo -e \"${{ secrets.SNOWFLAKE_ACCOUNT }}\")
          user = $(echo -e \"${{ secrets.SNOWFLAKE_USER }}\")
          password = $(echo -e \"${{ secrets.SNOWFLAKE_PASSWORD }}\")
          role = $(echo -e \"${{ secrets.SNOWFLAKE_ROLE_DEV }}\")
          warehouse = $(echo -e \"${{ secrets.SNOWFLAKE_WAREHOUSE_DEV }}\")
          database = $(echo -e \"${{ secrets.SNOWFLAKE_DATABASE_DEV }}\")
          schema = $(echo -e \"${{ secrets.SNOWFLAKE_SCHEMA_DEV }}\")
          client_session_keep_alive = true" >> streamlit/.streamlit/secrets.toml

      - name: Terraform Init
        working-directory: ./terraform  
        run: |
          terraform init  -var="key"=${{ secrets.key }} -var=ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }} -var=RESOURCE_GROUP_NAME=${{ secrets.RESOURCE_GROUP_NAME }} -var=STORAGE_ACCOUNT_NAME=${{ secrets.STORAGE_ACCOUNT_NAME }} -var=CLIENT_ID_AD=${{ secrets.CLIENT_ID_AD }} 

      - name: Terraform Plan  
        working-directory: ./terraform  
        run: | 
          terraform plan -no-color -var="CLIENT_ID_AD"=${{ secrets.CLIENT_ID_AD }}  -var="key"=${{ secrets.key }} -var=ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }} -var=RESOURCE_GROUP_NAME=${{ secrets.RESOURCE_GROUP_NAME }} -var=STORAGE_ACCOUNT_NAME=${{ secrets.STORAGE_ACCOUNT_NAME }} 
          
      - name: Terraform Apply
        working-directory: ./terraform
        run: |

          terraform apply -auto-approve -input=false  -var="CLIENT_ID_AD"=${{ secrets.CLIENT_ID_AD }}  -var="key"=${{ secrets.key }} -var=ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }} -var=RESOURCE_GROUP_NAME=${{ secrets.RESOURCE_GROUP_NAME }} -var=STORAGE_ACCOUNT_NAME=${{ secrets.STORAGE_ACCOUNT_NAME }}

