name: 'Terraform'

on:
  push:
    branches:
    - dev
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VERSION: latest

    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform
        run: |
          terraform init -var=RESOURCE_GROUP_NAME=${{ secrets.RESOURCE_GROUP_NAME }}

      - name: Terraform Plan
        working-directory: ./terraform  
        run: |

          terraform plan  -var=ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }} -var=RESOURCE_GROUP_NAME=${{ secrets.RESOURCE_GROUP_NAME }} -var=STORAGE_ACCOUNT_NAME=${{ secrets.STORAGE_ACCOUNT_NAME }} -var=SourceControlToken=${{ secrets.AZUREGITHUBTOKEN }}    -no-color -input=false
         
      - name: Terraform Apply
        working-directory: ./terraform
        run: |
          terraform apply -auto-approve -input=false  -var=ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }} -var=RESOURCE_GROUP_NAME=${{ secrets.RESOURCE_GROUP_NAME }} -var=STORAGE_ACCOUNT_NAME=${{ secrets.STORAGE_ACCOUNT_NAME }} -var=SourceControlToken=${{ secrets.AZUREGITHUBTOKEN }}